<a href="https://colab.research.google.com/github/R3Mi91/TSC/blob/main/Copia%20Equipo_2_Tarea_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Tarea 2***
### Equipo 2:
Integrantes:

*  Aguilar Zamacona Karol Esperanza
*  Ávila Sánchez Kaori Andrea
*  Guzmán Camargo Sofía
*  León Hernández Itzel Antea
*  López Medina Mariana Dolores
*  Mejia Pérez Alejandro Aldair
*  Real Marmolejo Gabriel
*  Reséndiz Martínez Irving
*  Ojeda Gómez Cristopher David
*  Silva Lopez Mauricio

# ***Tarea SQL lite***

Importamos las paqueterías a utilizar en el código

In [ ]:
pip install openpyxl

In [ ]:
import pandas as pd
import numpy as np
import sqlite3
import os
import sqlite3
import unicodedata
import seaborn as sns


Importamos los datos desde el Github, la base de datos está en 4 diferentes archivos, los cuales contienen las 4 diferentes tablas.

In [ ]:
Tabla_1= "https://raw.githubusercontent.com/R3Mi91/TSC/refs/heads/main/BaseCat_Tabla1.csv"
Tabla_2= "https://raw.githubusercontent.com/R3Mi91/TSC/refs/heads/main/BaseCat_Tabla2.csv"
Tabla_3= "https://raw.githubusercontent.com/R3Mi91/TSC/refs/heads/main/BaseCat_Tabla3.csv"
Tabla_4= "https://raw.githubusercontent.com/R3Mi91/TSC/refs/heads/main/BaseCat_Tabla4.csv"

Importamos las tablas a un formato de sql, con el fin de hacer las consultas desde la Base de Datos

In [ ]:
import sqlite3

hoja_Tabla1.to_sql('Tabla1', conn, if_exists='replace', index=False)
hoja_Tabla2.to_sql('Tabla2', conn, if_exists='replace', index=False)
hoja_Tabla3.to_sql('Tabla3', conn, if_exists='replace', index=False)
hoja_Tabla4.to_sql('Tabla4', conn, if_exists='replace', index=False)

128

Lee todos los registros de la tabla Tabla4 de la base SQLite BaseGat.db en un DataFrame y muestra las primeras filas.

In [ ]:
df = pd.read_sql_query("SELECT * FROM Tabla4", conn)
print(df.head())

   marca              nombre marca
0     16                    AQUEON
1     19              AVIAN SELECT
2     49  CONCEPTUAL CREATIONS PET
3     73               FANCY FEAST
4     95                     HAGEN


Muestra todo el contenido del DataFrame df, es decir, todos los registros de la tabla Tabla4.

In [ ]:
print(df)

     marca              nombre marca
0       16                    AQUEON
1       19              AVIAN SELECT
2       49  CONCEPTUAL CREATIONS PET
3       73               FANCY FEAST
4       95                     HAGEN
..     ...                       ...
123   1186              GOOD N TASTY
124   1187   LIFE PROTECTION FORMULA
125   1188                 TASTEFULS
126   1190                SUPER DEGY
127   1191                  FERPLAST

[128 rows x 2 columns]


# Creación de la Tabla reporte

LEFT JOIN de Tabla2 con Tabla1

Realizamos un LEFT JOIN entre Tabla1 y Tabla2 usando la columna Material, selecciona Tienda y Material de Tabla1 y Nombre Material y Marca de Tabla2, con el fin de guardar el resultado en un DataFrame df_union para mostrarlo.

In [ ]:
query = """
SELECT
    t1.'Tienda',
    t1.'Material',
    t2.'Nombre Material',
    t2.'Marca'
FROM Tabla1 t1
LEFT JOIN Tabla2 t2 ON t1.Material = t2.Material
"""
df_union = pd.read_sql_query(query, conn)
display(df_union)

Tienda  Material                           Nombre Material  Marca
0      7117    105012  HOJUELA P/PEZ TROPICAL 330ML                287
1      7117    105013  MICRO PELLET P/PEZ BETTA 10ML               287
2      7117    105014  MICRO PELLET P/PEZ BETTA 30ML               287
3      7117    105015  MICRO PELLET P/PEZ TROP 120ML               287
4      7117    105021  PELLET COLORANTE P/PEZ 330ML                287
..      ...       ...                                       ...    ...
188    7171    127165  PELET FLOTANT BETTA 0.1OZ/2.8G              255
189    7171    127871  AZOOPLUS DELICAMARON CRIAS 20G              287
190    7171    129483  TUBIFEX WORM 220ML 30G                      287
191    7171    129484  BLOOD WORMS 22OML 20G                       287
192    7171    142594  BETTA PRO DELICIAS CAMARON 20G              287

[193 rows x 4 columns]

LEFT JOIN de Tabla4 con Tabla2

Ahora realizaremos un LEFT JOIN encadenado une Tabla1 con Tabla2 por Material y luego con Tabla4 por Marca, seleccionando Tienda y Material de Tabla1, Nombre Material y Marca de Tabla2, y nombre marca de Tabla4, guardando el resultado en df_2union y mostrándolo.

In [ ]:
query = """
SELECT *
FROM Tabla1 t1
LEFT JOIN Tabla2 t2 ON t1.Material = t2.Material
LEFT JOIN Tabla4 t4 ON t2.Marca = t4.marca
"""
df_2union = pd.read_sql_query(query, conn)
display(df_2union)

Tienda  Material  Material                           Nombre Material  \
0      7117    105012    105012  HOJUELA P/PEZ TROPICAL 330ML               
1      7117    105013    105013  MICRO PELLET P/PEZ BETTA 10ML              
2      7117    105014    105014  MICRO PELLET P/PEZ BETTA 30ML              
3      7117    105015    105015  MICRO PELLET P/PEZ TROP 120ML              
4      7117    105021    105021  PELLET COLORANTE P/PEZ 330ML               
..      ...       ...       ...                                       ...   
188    7171    127165    127165  PELET FLOTANT BETTA 0.1OZ/2.8G             
189    7171    127871    127871  AZOOPLUS DELICAMARON CRIAS 20G             
190    7171    129483    129483  TUBIFEX WORM 220ML 30G                     
191    7171    129484    129484  BLOOD WORMS 22OML 20G                      
192    7171    142594    142594  BETTA PRO DELICIAS CAMARON 20G             

     Marca  marca nombre marca  
0      287    287         AZOO  
1      287    287         AZOO  
2      287    287         AZOO  
3      287    287         AZOO  
4      287    287         AZOO  
..     ...    ...          ...  
188    255    255      ZOO MED  
189    287    287         AZOO  
190    287    287         AZOO  
191    287    287         AZOO  
192    287    287         AZOO  

[193 rows x 7 columns]

Finalmente crearemos de la tabla reporte completa sobre la que se harán las consultas

Realizaremo un LEFT JOIN entre REPORTE_TDA_MARCAS y Tabla3 usando la columna Tienda, seleccionando todas las columnas de interés de ambos DataFrames (información de material, marca y ventas por mes) y guarda el resultado en df_final_report para mostrarlo.

In [ ]:
query = """
SELECT
    t1.Tienda,
    t1.Material,
    t2."Nombre Material",
    t2.Marca,
    t4."nombre marca",
    t3."nombre tienda",
    t3.Distrito,
    t3.Estado,
    t3."Enero 2025",
    t3."Febrero 2025",
    t3."Marzo 2025",
    t3."Abril 2025",
    t3."Mayo 2025",
    t3."Junio 2025",
    t3."Julio 2025",
    t3."Agosto 2025",
    t3."Septiembre 2025",
    t3."Octubre 2025"
FROM Tabla1 t1
LEFT JOIN Tabla2 t2 ON t1.Material = t2.Material
LEFT JOIN Tabla4 t4 ON t2.Marca = t4.marca
LEFT JOIN Tabla3 t3 ON t1.Tienda = t3.Tienda
"""
df_final_report = pd.read_sql_query(query, conn)
df_final_report.to_sql('REPORTE_TDA_MARCAS', conn, if_exists='replace', index=False)
display(df_final_report)

Tienda  Material                           Nombre Material  Marca  \
0      7117    105012  HOJUELA P/PEZ TROPICAL 330ML                287   
1      7117    105013  MICRO PELLET P/PEZ BETTA 10ML               287   
2      7117    105014  MICRO PELLET P/PEZ BETTA 30ML               287   
3      7117    105015  MICRO PELLET P/PEZ TROP 120ML               287   
4      7117    105021  PELLET COLORANTE P/PEZ 330ML                287   
..      ...       ...                                       ...    ...   
188    7171    127165  PELET FLOTANT BETTA 0.1OZ/2.8G              255   
189    7171    127871  AZOOPLUS DELICAMARON CRIAS 20G              287   
190    7171    129483  TUBIFEX WORM 220ML 30G                      287   
191    7171    129484  BLOOD WORMS 22OML 20G                       287   
192    7171    142594  BETTA PRO DELICIAS CAMARON 20G              287   

    nombre marca nombre tienda Distrito Estado  Enero 2025  Febrero 2025  \
0           AZOO  Lomas Verdes     D-03    MEX      4307.0        4130.0   
1           AZOO  Lomas Verdes     D-03    MEX      4307.0        4130.0   
2           AZOO  Lomas Verdes     D-03    MEX      4307.0        4130.0   
3           AZOO  Lomas Verdes     D-03    MEX      4307.0        4130.0   
4           AZOO  Lomas Verdes     D-03    MEX      4307.0        4130.0   
..           ...           ...      ...    ...         ...           ...   
188      ZOO MED     Echegaray     D-03    MEX      2815.0        2762.0   
189         AZOO     Echegaray     D-03    MEX      2815.0        2762.0   
190         AZOO     Echegaray     D-03    MEX      2815.0        2762.0   
191         AZOO     Echegaray     D-03    MEX      2815.0        2762.0   
192         AZOO     Echegaray     D-03    MEX      2815.0        2762.0   

     Marzo 2025  Abril 2025  Mayo 2025  Junio 2025  Julio 2025  Agosto 2025  \
0        4883.0      4754.0     4217.0      5045.0      4321.0       1884.0   
1        4883.0      4754.0     4217.0      5045.0      4321.0       1884.0   
2        4883.0      4754.0     4217.0      5045.0      4321.0       1884.0   
3        4883.0      4754.0     4217.0      5045.0      4321.0       1884.0   
4        4883.0      4754.0     4217.0      5045.0      4321.0       1884.0   
..          ...         ...        ...         ...         ...          ...   
188      3048.0      3258.0     3365.0      3145.0      3432.0       3194.0   
189      3048.0      3258.0     3365.0      3145.0      3432.0       3194.0   
190      3048.0      3258.0     3365.0      3145.0      3432.0       3194.0   
191      3048.0      3258.0     3365.0      3145.0      3432.0       3194.0   
192      3048.0      3258.0     3365.0      3145.0      3432.0       3194.0   

     Septiembre 2025  Octubre 2025  
0             2841.0        2128.0  
1             2841.0        2128.0  
2             2841.0        2128.0  
3             2841.0        2128.0  
4             2841.0        2128.0  
..               ...           ...  
188           2660.0        1770.0  
189           2660.0        1770.0  
190           2660.0        1770.0  
191           2660.0        1770.0  
192           2660.0        1770.0  

[193 rows x 18 columns]

# Consultas

Consulta 1. Filtrado de las ventas de las tiendas que fueron menores a 4000 en el mes de abril de 2025

Obtiene filas únicas de REPORTE_TDA_MARCAS unidas con Tabla3, mostrando la tienda y sus ventas de abril 2025 solo si son menores a 4000, y ordena el resultado de mayor a menor ventas en df_distinct_filtered_report.

In [ ]:
query = """
SELECT DISTINCT
    rtm.Tienda,
    t3."nombre tienda",
    t3."Abril 2025" AS Ventas_Abril_2025
FROM REPORTE_TDA_MARCAS rtm
LEFT JOIN Tabla3 t3 ON rtm.Tienda = t3.Tienda
WHERE t3."Abril 2025" < 4000
ORDER BY Ventas_Abril_2025 DESC
"""
df_distinct_filtered_report = pd.read_sql_query(query, conn)
display(df_distinct_filtered_report)

Tienda nombre tienda  Ventas_Abril_2025
0    7127       Mundo E             3858.1
1    7155     El Dorado             3663.0
2    7123      Satelite             3292.0
3    7171     Echegaray             3258.0

Consulta 2. Reporte de las materiales que produce la marca de nombre AZOO y id 287

Filtra filas únicas de REPORTE_TDA_MARCAS donde Marca es 287 y el nombre de la marca contiene "AZOO", seleccionando Marca, nombre marca, Material y Nombre Material, y guarda el resultado en df_azoo_reporte.

In [ ]:
query = """
SELECT DISTINCT
    Marca,
    "nombre marca",
    Material,
    "Nombre Material"
FROM REPORTE_TDA_MARCAS
WHERE Marca = 287
AND "nombre marca" LIKE '%AZOO%'
"""
df_azoo_reporte = pd.read_sql_query(query, conn)
display(df_azoo_reporte)

Marca nombre marca  Material                           Nombre Material
0     287         AZOO    105012  HOJUELA P/PEZ TROPICAL 330ML            
1     287         AZOO    105013  MICRO PELLET P/PEZ BETTA 10ML           
2     287         AZOO    105014  MICRO PELLET P/PEZ BETTA 30ML           
3     287         AZOO    105015  MICRO PELLET P/PEZ TROP 120ML           
4     287         AZOO    105021  PELLET COLORANTE P/PEZ 330ML            
5     287         AZOO    105027  PELLET P/GUPPIES 120ML                  
6     287         AZOO    105029  PELLET P/PEZ GOLDFISH 120ML             
7     287         AZOO    105030  PELLET P/PEZ GOLDFISH 2000ML            
8     287         AZOO    105031  PELLET P/PEZ GOLDFISH 330ML             
9     287         AZOO    105034  PELLET P/PEZ TROPICAL 330ML             
10    287         AZOO    105036  PELLET P/TORTUGA 120ML                  
11    287         AZOO    105037  PELLET P/TORTUGA 330ML                  
12    287         AZOO    105038  PELLET P/TORTUGA 900ML                  
13    287         AZOO    105039  PELLET P/TORTUGA PEQ 120ML              
14    287         AZOO    105040  PELLET P/TORTUGA PEQ 330ML              
15    287         AZOO    114989  ALIMENTO PECES FLUORESCEN 53GR          
16    287         AZOO    114990  PELLET P/PEZ FLUORESCENTE 330ML         
17    287         AZOO    114993  9 IN 1 PELLET P/CREC KOI 1KG            
18    287         AZOO    118238  BETTA CUISINE 25GR                      
19    287         AZOO    120978  AZOOPLUS PECES TROPICALES 53G           
20    287         AZOO    120980  AZOOPLUS TROPICAL BITS 53G              
21    287         AZOO    120981  AZOOPLUS TROPICAL BITS 130G             
22    287         AZOO    120983  AZOOPLUS CARNIVOROS 100G                
23    287         AZOO    120985  ZOOPLUS MIGNON GUPPIES 53G              
24    287         AZOO    120989  AZOOPLUS GOLDFISH PREMIUM 122G          
25    287         AZOO    120990  AZOOPLUS GOLDFISH PREMIUM 425G          
26    287         AZOO    123961  AZOOPLUS TROP SHRIMP PIE 58G            
27    287         AZOO    123964  ALIM CRECIMIENTO GAMBAS 10G             
28    287         AZOO    127871  AZOOPLUS DELICAMARON CRIAS 20G          
29    287         AZOO    129483  TUBIFEX WORM 220ML 30G                  
30    287         AZOO    129484  BLOOD WORMS 22OML 20G                   
31    287         AZOO    142594  BETTA PRO DELICIAS CAMARON 20G

Consulta 3. Reporte de las tiendas que venden marca ZOO MED.

Obtiene filas únicas de REPORTE_TDA_MARCAS unidas con Tabla3 donde Marca es 255 y el nombre marca es "ZOO MED", mostrando información de tienda, material, marca, distrito y estado, y guarda el resultado en df_zoo_med_reporte.

In [ ]:
query = """
SELECT DISTINCT
    rtm.Tienda,
    rtm.Marca,
    rtm."nombre marca",
    rtm.Material,
    rtm."Nombre Material",
    t3."nombre tienda",
    t3.Distrito,
    t3.Estado
FROM REPORTE_TDA_MARCAS rtm
LEFT JOIN Tabla3 t3 ON rtm.Tienda = t3.Tienda
WHERE rtm.Marca = 255
AND rtm."nombre marca" = 'ZOO MED'
"""
df_zoo_med_reporte = pd.read_sql_query(query, conn)
display(df_zoo_med_reporte)

Tienda  Marca nombre marca  Material  \
0    7117    255      ZOO MED    127165   
1    7123    255      ZOO MED    127165   
2    7127    255      ZOO MED    127165   
3    7155    255      ZOO MED    127165   
4    7171    255      ZOO MED    127165   

                            Nombre Material nombre tienda Distrito Estado  
0  PELET FLOTANT BETTA 0.1OZ/2.8G            Lomas Verdes     D-03    MEX  
1  PELET FLOTANT BETTA 0.1OZ/2.8G                Satelite     D-03    MEX  
2  PELET FLOTANT BETTA 0.1OZ/2.8G                 Mundo E     D-03    MEX  
3  PELET FLOTANT BETTA 0.1OZ/2.8G               El Dorado     D-03    MEX  
4  PELET FLOTANT BETTA 0.1OZ/2.8G               Echegaray     D-03    MEX

Consulta 4. Reporte de todos los materiales que tienen una A como inicial y se venden en las tiendas de ID mayor a 7127

Filtra de REPORTE_TDA_MARCAS las filas donde Nombre Material empieza con "A" y Tienda es mayor a 7127, seleccionando solo Tienda y Nombre Material, y guarda el resultado en df_filtered_materials.

In [ ]:
query = """
SELECT
    Tienda,
    "Nombre Material"
FROM REPORTE_TDA_MARCAS
WHERE "Nombre Material" LIKE 'A%'
AND Tienda > 7127
"""
df_filtered_materials = pd.read_sql_query(query, conn)
display(df_filtered_materials)

Tienda                           Nombre Material
0     7155  ALIMENTO PECES FLUORESCEN 53GR          
1     7155  AZOOPLUS PECES TROPICALES 53G           
2     7155  AZOOPLUS TROPICAL BITS 53G              
3     7155  AZOOPLUS TROPICAL BITS 130G             
4     7155  AZOOPLUS CARNIVOROS 100G                
5     7155  AZOOPLUS GOLDFISH PREMIUM 122G          
6     7155  AZOOPLUS GOLDFISH PREMIUM 425G          
7     7155  AZOOPLUS TROP SHRIMP PIE 58G            
8     7155  ALIM CRECIMIENTO GAMBAS 10G             
9     7155  AZOOPLUS DELICAMARON CRIAS 20G          
10    7171  ALIMENTO PECES FLUORESCEN 53GR          
11    7171  AZOOPLUS PECES TROPICALES 53G           
12    7171  AZOOPLUS TROPICAL BITS 53G              
13    7171  AZOOPLUS TROPICAL BITS 130G             
14    7171  AZOOPLUS CARNIVOROS 100G                
15    7171  AZOOPLUS GOLDFISH PREMIUM 122G          
16    7171  AZOOPLUS GOLDFISH PREMIUM 425G          
17    7171  AZOOPLUS TROP SHRIMP PIE 58G            
18    7171  ALIM CRECIMIENTO GAMBAS 10G             
19    7171  AZOOPLUS DELICAMARON CRIAS 20G

Consulta 5.- Reporte la cantidad de materiales que hay por tienda

In [ ]:
query = """
SELECT "Nombre Tienda", count("Nombre Material") as No_Material
FROM Reporte_TDA_Marcas
GROUP BY "Nombre Tienda"
"""
df_tabla_no_materiales = pd.read_sql_query(query, conn)
display(df_tabla_no_materiales)

nombre tienda  No_Material
0     Echegaray           33
1     El Dorado           31
2  Lomas Verdes           33
3        Miyana           30
4       Mundo E           33
5      Satelite           33

### *Reporte de la base de datos*

In [ ]:
pip install dash

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 51.4 MB/s eta 0:00:00


Con el fin
La consulta crea un dashboard interactivo con Dash que muestra cuatro visualizaciones basadas en los DataFrames obtenidos de la base de datos: un gráfico de barras con las tiendas cuyas ventas en abril 2025 fueron menores a 4000, un histograma de los materiales producidos por la marca AZOO, un gráfico sunburst que representa la distribución de la marca ZOO MED por Estado, Distrito y tienda, y un diagrama de dispersión de los materiales cuyo nombre empieza con “A”. Todas las gráficas se organizan verticalmente bajo un título principal, y la aplicación se ejecuta localmente para permitir la interacción con las visualizaciones.

In [ ]:
import dash
from dash import dcc, html
import plotly.express as px

app = dash.Dash(__name__)

fig_abril = px.bar(df_distinct_filtered_report, x='nombre tienda', y='Ventas_Abril_2025', title='Tiendas con ventas < 4000 en Abril')
fig_azoo = px.histogram(df_azoo_reporte, x='Nombre Material', title='Materiales producidos por AZOO')
fig_zoo = px.sunburst(df_zoo_med_reporte, path=['Estado', 'Distrito', 'nombre tienda'], title='Distribución ZOO MED')
fig_materiales_a = px.scatter(df_filtered_materials, x='Tienda', y='Nombre Material', title='Materiales que empiezan con A')

app.layout = html.Div([
    html.H1("Dashboard de Ventas y Marcas"),
    dcc.Graph(figure=fig_abril),
    dcc.Graph(figure=fig_azoo),
    dcc.Graph(figure=fig_zoo),
    dcc.Graph(figure=fig_materiales_a)
])

if __name__ == '__main__':
    app.run(debug=True)

<IPython.core.display.Javascript object>

# ***Tarea SAS***

### A continuación se adjunta el código de SAS como comentario en la linea de código dentro del notebook, con el fin de no perder la identación, espacios y orden de nuestro código.

In [ ]:
"""*********************************************************************
*********** Cargamos los datos del archivo xlsx a tablas ************
*********************************************************************;

data tienda_materiales;
	input Tienda  Material;
	datalines;
      7117    105012
      7117    105013
      7117    105014
      7117    105015
      7117    105021
      7117    105027
      7117    105029
      7117    105030
      7117    105031
      7117    105034
      7117    105036
      7117    105037
      7117    105038
      7117    105039
      7117    105040
      7117    114989
      7117    114990
      7117    114993
      7117    118238
      7117    120978
      7117    120980
      7117    120981
      7117    120983
      7117    120985
      7117    120989
      7117    120990
      7117    123961
      7117    123964
      7117    127165
      7117    127871
      7117    129483
      7117    129484
      7117    142594
      7120    105012
      7120    105013
      7120    105014
      7120    105015
      7120    105021
      7120    105027
      7120    105029
      7120    105030
      7120    105031
      7120    105034
      7120    105036
      7120    105037
      7120    105039
      7120    114989
      7120    114990
      7120    114993
      7120    118238
      7120    120978
      7120    120980
      7120    120981
      7120    120983
      7120    120985
      7120    120989
      7120    120990
      7120    123961
      7120    123964
      7120    127871
      7120    129483
      7120    129484
      7120    142594
      7123    105012
      7123    105013
      7123    105014
      7123    105015
      7123    105021
      7123    105027
      7123    105029
      7123    105030
      7123    105031
      7123    105034
      7123    105036
      7123    105037
      7123    105038
      7123    105039
      7123    105040
      7123    114989
      7123    114990
      7123    114993
      7123    118238
      7123    120978
      7123    120980
      7123    120981
      7123    120983
      7123    120985
      7123    120989
      7123    120990
      7123    123961
      7123    123964
      7123    127165
      7123    127871
      7123    129483
      7123    129484
      7123    142594
      7127    105012
      7127    105013
      7127    105014
      7127    105015
      7127    105021
      7127    105027
      7127    105029
      7127    105030
      7127    105031
      7127    105034
      7127    105036
      7127    105037
      7127    105038
      7127    105039
      7127    105040
      7127    114989
      7127    114990
      7127    114993
      7127    118238
      7127    120978
      7127    120980
      7127    120981
      7127    120983
      7127    120985
      7127    120989
      7127    120990
      7127    123961
      7127    123964
      7127    127165
      7127    127871
      7127    129483
      7127    129484
      7127    142594
      7155    105012
      7155    105013
      7155    105014
      7155    105015
      7155    105021
      7155    105027
      7155    105029
      7155    105030
      7155    105031
      7155    105034
      7155    105036
      7155    105037
      7155    105040
      7155    114989
      7155    114990
      7155    114993
      7155    118238
      7155    120978
      7155    120980
      7155    120981
      7155    120983
      7155    120985
      7155    120989
      7155    120990
      7155    123961
      7155    123964
      7155    127165
      7155    127871
      7155    129483
      7155    129484
      7155    142594
      7171    105012
      7171    105013
      7171    105014
      7171    105015
      7171    105021
      7171    105027
      7171    105029
      7171    105030
      7171    105031
      7171    105034
      7171    105036
      7171    105037
      7171    105038
      7171    105039
      7171    105040
      7171    114989
      7171    114990
      7171    114993
      7171    118238
      7171    120978
      7171    120980
      7171    120981
      7171    120983
      7171    120985
      7171    120989
      7171    120990
      7171    123961
      7171    123964
      7171    127165
      7171    127871
      7171    129483
      7171    129484
      7171    142594
;


data materiales_marcas;
	input Material 1-7 'Nombre Material'n $ 8-48 Marca 49-52;
	datalines;
101275	PLATO AZUL PARA REPTIL                  	445
101277	PLATO C/FORMA DE RINON MD               	445
101335	RACIMO MORADO                           	445
101340	PLANTA VERANO NATURAL                   	445
101369	PLANTA PLAST VERDE/ RJ                  	445
101374	VASIJA EGIPCIA                          	445
101376	CORTAUNA P/REPTIL                       	445
101387	PLATO BRILLANTE P/REPTIL                	49
101435	PIEDRA AIREADORA 12"                    	445
101444	FORMADOR BURBUJA 14"                    	445
101463	FORMADOR BURBUJA 18"                    	445
101478	TERMOMETRO EXTERIOR                     	445
101479	TERMOMETRO C/VENTOSA                    	445
101490	AIREADOR DONA 10CM                      	445
101496	RUINAS TEMPLO GRIEGO MED                	445
101501	ESCOND 3 NIVELES NARANJA                	445
101503	BOWL TRONCO REPTIL                      	170
101512	PLANTA AMBULIA VERDE CHI                	445
101516	PLANTA LUDWIG/MUSGO CHI                 	445
101518	PLANTA AMAZONICA CHI                    	445
101530	PASTO DECORATIVO MED                    	445
101546	PASTO DECORATIVO 6PZ                    	445
101559	RUINAS PERDIDAS CHI                     	445
101562	CUBO RUSTICO DECORATIVO                 	445
101577	TRONCO C/BASE GRANDE                    	445
101580	ANCLA DE MAR                            	445
101615	RUINAS CASA D/CAMBODIA                  	445
101622	SOPORTE P/JIBIA - MIJO CH               	621
101627	BEBEDERO JUMBO P/AVE 118ML              	621
101631	BEBEDERO JUMBO P/AVE 414ML              	621
101644	JUG P/HURON 6PZ                         	621
101646	HAMACA P/HURON 36CM                     	621
101656	TUNEL 76CM P/HURON MED                  	243
101660	GARY - BOB ESPONJA DECORATIVO           	161
101665	COMED TWIST & LOCK 567GR                	128
101734	PIEDRA ZEOLITE CRYSTAL 510GR            	445
101773	JAULA NEGRA PERMANENTE P/NINFA          	621
101777	JAULA P/LORITO CUADRADA                 	621
101780	JAULA CAFE P/LORITO RANCHO              	621
101782	JAULA P/LORITO FAUX                     	621
101786	HABITAT CRITTER TAIL ONE                	114
101791	CRITTERTAIL HAMSTER KIT TWO             	114
101794	CRITTERTAIL HAMSTER KIT Z               	114
101797	MEDIDOR TEMPERATURA P/REPTIL            	445
101799	COMBO MEDIDOR TEMP/HUMED                	445
101800	MEDIDOR HUMEDAD P/REPTIL                	445
101807	BOWL DRUM DELUXE P/BETTA 3.78L          	445
101821	CLIP P/PREMIO 4PZ                       	621
101823	BEBEDERO SILO 15CM                      	621
101832	CAMA POLAR ROEDORES                     	621
105012	HOJUELA P/PEZ TROPICAL 330ML            	287
105013	MICRO PELLET P/PEZ BETTA 10ML           	287
105014	MICRO PELLET P/PEZ BETTA 30ML           	287
105015	MICRO PELLET P/PEZ TROP 120ML           	287
105021	PELLET COLORANTE P/PEZ 330ML            	287
105027	PELLET P/GUPPIES 120ML                  	287
105029	PELLET P/PEZ GOLDFISH 120ML             	287
105030	PELLET P/PEZ GOLDFISH 2000ML            	287
105031	PELLET P/PEZ GOLDFISH 330ML             	287
105034	PELLET P/PEZ TROPICAL 330ML             	287
105036	PELLET P/TORTUGA 120ML                  	287
105037	PELLET P/TORTUGA 330ML                  	287
105038	PELLET P/TORTUGA 900ML                  	287
105039	PELLET P/TORTUGA PEQ 120ML              	287
105040	PELLET P/TORTUGA PEQ 330ML              	287
114989	ALIMENTO PECES FLUORESCEN 53GR          	287
114990	PELLET P/PEZ FLUORESCENTE 330ML         	287
114993	9 IN 1 PELLET P/CREC KOI 1KG            	287
118238	BETTA CUISINE 25GR                      	287
120978	AZOOPLUS PECES TROPICALES 53G           	287
120980	AZOOPLUS TROPICAL BITS 53G              	287
120981	AZOOPLUS TROPICAL BITS 130G             	287
120983	AZOOPLUS CARNIVOROS 100G                	287
120985	ZOOPLUS MIGNON GUPPIES 53G              	287
120989	AZOOPLUS GOLDFISH PREMIUM 122G          	287
120990	AZOOPLUS GOLDFISH PREMIUM 425G          	287
123961	AZOOPLUS TROP SHRIMP PIE 58G            	287
123964	ALIM CRECIMIENTO GAMBAS 10G             	287
127165	PELET FLOTANT BETTA 0.1OZ/2.8G          	255
127871	AZOOPLUS DELICAMARON CRIAS 20G          	287
129483	TUBIFEX WORM 220ML 30G                  	287
129484	BLOOD WORMS 22OML 20G                   	287
142594	BETTA PRO DELICIAS CAMARON 20G          	287
;
run;


data Ventas;
    length 'nombre tienda'n $30 Distrito $5 Estado $3;
    input Tienda
          'nombre tienda'n $&30.
          Distrito $
          Estado $
          'Enero 2025'n
          'Febrero 2025'n
          'Marzo 2025'n
          'Abril 2025'n
          'Mayo 2025'n
          'Junio 2025'n
          'Julio 2025'n
          'Agosto 2025'n
          'Septiembre 2025'n
          'Octubre 2025'n;
    datalines;
7101 López Mateos     D-07 JAL 10253 10733 12573 12958 11821 13551 12680 15338 12657  7517
7102 Santa Fe         D-01 DF  08814  6740  8290  6361  9464  9056  8215  8913  7663  6282
7103 Universidad      D-04 DF  06716  6238  8476  7822  8517  7372  7438  6937  6021  4337
7104 Vasconcelos      D-09 NL  05986  5609  5966  5128  6955  6341  6454  5275  5253  2726
7105 Miramontes       D-04 DF  04804  4403  4829  5352  5745  5500  4638  5659  4748  2914
7106 Américas         D-07 JAL 06031  5997  6244  8151  7608  8819 10356  8710  8414  4801
7107 Condesa (Exp)    D-02 DF  00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7108 Oasis Coyoacán   D-04 DF  06671  5370  7517  5898  6738  6689  6838  6179  5801  3532
7109 Pedregal (Exp)   D-02 DF  00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7110 P.S. Jerónimo    D-02 DF  00003  0002  0000  0000  0000  0000  0000  0000  0000  0000
7111 Interlomas       D-03 MEX 02665  3615  3947  3455  5781  4797  4429  3740  4652  2860
7112 San Pedro        D-09 NL  05058  2936  3696  4279  4516  4999  4729  5055  4945  3021
7113 Acueducto        D-07 JAL 07391  6723  9705 10013  9171  1778  1453  1527  1197   767
7114 Serena           D-08 NL  03810  3525  6582  4380  3772  4402  3280  4695  3232  1986
7115 León             D-06 GTO 10976  8416  8788  9219  7897  7017  6293  8152  5787  4190
7116 Juriquilla       D-05 QRO 08977  8869  9909 11525 10142 10756  8498  2294  1736  1064
7117 Lomas Verdes     D-03 MEX 04307  4130  4883  4754  4217  5045  4321  1884  2841  2128
7118 Puebla           D-12 PUE 05731  5442  6028  4108  5375  4649  4965  5272  1291   984
7119 La Rioja         D-07 JAL 07161  5562  6068  7830  8979  7652  7390  7072  5419  4297
7120 Miyana           D-03 DF  11304  8877 11222 11232 10442  7663  9375  8987  8209  5661
7121 Esmeralda        D-03 MEX 04580  3632  6002  4509  5245  4895  4533  5163  5196  3543
7122 Sania (Exp)      D-07 JAL 00003  0000  0002  0000  0000  0000  0000  0000  0000  0000
7123 Satelite         D-03 MEX 02293  2578  3073  3292  2834  2667  2772  3470  2137  1417
7124 Angelópolis      D-12 PUE 04371  4528  5228  6177  5678  5202  6143  5340  6324  4013
7125 Saltillo         D-09 COA 06031  5545  6953  7923  9719  7482  8694  8395  7080  4337
7126 Arenal           D-04 DF  01892  1191  1384  1672  1773  1785  1877  1533  1578   705
7127 Mundo E          D-03 MEX 03726  3306  3169  3858  4431  3575  3430  3434  3639  1698
7128 Fortuna          D-01 DF  03027  4008  3523  3855  3722  3321  3595  3143  2780  1800
7129 Mixcoac          D-04 DF  04924  4720  5224  5059  6396  6585  5764  4613  3210  2650
7130 Condesa II       D-02 DF  00001  0004  0001  0000  0000  0000  0000  0000  0000  0000
7131 Cumbres          D-08 NL  04956  6172  6107  5872  6151  6535  7119  5993  5870  3704
7132 Mérida           D-13 YUC 06948  6013  6334  5225  7300  5439  7184  6504  5456  3738
7133 San Luis Potosí  D-06 SLP 08657  7222  8117  4569  7529  7356  6011  7525  7538  4456
7134 V. Hermosa       D-03 DF  00001  0002  0000  0001  0000  0000  0000  0000  0000  0000
7135 SM Allende I     D-05 GTO 00134   093   068   092   059   082   067   097   048   028
7136 Irapuato         D-06 GTO 03453  2458  4140  4099  4048  5512  4762  3487  4526  2370
7137 Metepec          D-01 MEX 03260  2986  3394  3016  3972  4768  4992  4084  3694  1947
7138 Pachuca          D-01 HGO 06049  5844  7385  7147  7555  6249  6132  4651  5788  3845
7139 Ajusco (Exp)     D-02 DF  00000  0001  0000  0000  0000  0000  0000  0000  0000  0000
7140 Viveros (Exp)    D-04 DF  00071   044   043   044   020   001   000   000   000   000
7141 B. Quintana      D-05 QRO 00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7142 Culiacán         D-11 SIN 01994  1685  2002  2341  2686  1517  1925  2209  2256  1453
7143 Averanda         D-04 MOR 05727  4996  4554  4179  5279  5891  5412  5919  4484  2734
7144 La Victoria      D-05 QRO 05948  4954  6111  5093  6540  6465  6472  7473  7321  4492
7145 Tecamach. (Exp)  D-03 MEX 00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7146 Morelia          D-05 MCH 03691  3857  3831  4005  4322  4039  5205  4825  4015  2482
7147 Paseo Hipódromo  D-03 MEX 02824  2578  2810  2852  2337  2074  1981  2660  2845  1648
7148 Chihuahua        D-11 CHI 06809  6828  6547  7814  9381  7441  8813  6201  3512  2703
7149 Mazatlán         D-11 SIN 03171  2689  2707  3871  5452  3685  3966  2792  2167  1673
7150 San Nicolás      D-09 NL  03462  2465  3405  3260  3929  3090  3608  3063  2442  1599
7151 Tuxtla           D-12 CHS 03526  2587  3806  3742  3981  3738  4303  3450  3209  3178
7152 Hermosillo       D-11 SON 04306  4053  4415  3413  4623  4024  4482  3904  3538  1877
7153 Garza Sada       D-08 NL  05452  5003  5260  5517  6896  7542  7534  6954  6637  3848
7154 Pas. Montejo     D-13 YUC 00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7155 El Dorado        D-03 MEX 04099  3170  4327  3663  3055  4072  3700  3267  2935  2111
7156 Xalapa           D-12 VER 02909  3162  2948  3530  2889  2393  2595  2757  2196  2002
7157 Patio Tlalpan    D-04 DF  02712  2404  2950  2704  2599  3075  2844  2936  2135  1133
7158 Jard Pedregal    D-02 DF  05478  5520  6005  7266  7643  7039  6844  6958  6295  3166
7159 P. La Mexic.     D-01 DF  00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7160 Aguilas (Exp)    D-02 DF  00002  0004  0002  0000  0000  0000  0000  0000  0000  0000
7162 Cordilleras      D-07 JAL 00000  0002  0001  0001  0000  0000  0000  0000  0000  0000
7163 Gonzalitos       D-09 NL  02827  2778  3098  3403  4297  3938  4151  2959  3110  2005
7165 Puerto Vallarta  D-07 JAL 04592  4439  4626  5494  6139  5757  5705  5403  4312  2673
7166 Aguascalientes   D-06 AGS 05386  4459  5491  5704  5285  5833  4915  5745  5208  3090
7167 Nuevo Anáhuac    D-09 NL  04449  4227  4348  4521  5037  5213  4879  4488  4100  2811
7168 Cúspide (Exp)    D-03 MEX 00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7169 Metrópoli (Exp)  D-02 DF  00001  0006  0001  0003  0002  0003  0000  0000  0000  0000
7170 Punto Maq (Exp)  D-04 DF  00002  0001  0002  0006  0001  0001  0006  0000  0000  0000
7171 Echegaray        D-03 MEX 02815  2762  3048  3258  3365  3145  3432  3194  2660  1770
7172 Cancún           D-13 QR  06957  6237  6852  7693  8621  7558  6215  7687  8332  4268
7173 Tlatelolco       D-01 DF  00001  0001  0001  0000  0000  0000  0000  0000  0000  0000
7174 Río Mayo (Exp)   D-04 MOR 00002  0000  0000  0000  0000  0000  0000  0000  0000  0000
7175 Medellín 333     D-02 DF  00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7176 Pab. Altavista   D-02 DF  00004  0002  0003  0000  0002  0001  0001  0001  0000  0000
7177 Torreón          D-11 COA 04960  5435  7322  6792  9320  8464  7791  9427  7484  3890
7178 Harbor           D-13 YUC 04878  4283  6280  5888  6387  5448  6369  7684  6124  3959
7179 Avila Camacho    D-07 JAL 04767  3840  3513  4825  5950  4696  6024  5158  4154  2345
7180 Villahermosa     D-12 TAB 07752  8250  9781  9489  8979 11277 10812  6355  8330  4998
7181 Coapa            D-04 DF  04633  4113  4527  4932  5812  5200  5127  5191  3605  2548
7183 La Viga          D-01 DF  02762  2050  3268  2224  2479  2496  2191  3143  2399  1323
7184 Celaya           D-05 GTO 03970  3680  4647  3978  5097  4561  4711  4085  4872  2699
7185 Boca del Río     D-12 VER 04356  4541  5106  5361  6039  5153  4991  5081  6364  3287
7186 Tijuana Vía Ráp  D-10 BC  10959  9200 10870 10638 11794 11765 12748 12147 11977  7767
7187 Mexicali         D-10 BC  06877  6321  8011  7328  8811  9730  9060  9673  9185  4607
7188 Lindavista       D-08 NL  00000   042   783  1094  1401  1660  1529  1576   935   000
7189 Cuitláhuac       D-01 DF  02685  1962  2716  2436  2179  2718  2088  2108  2112  1480
7190 Tepatitlán       D-07 JAL 00002  0002  0003  0005  0003  0008  0002  0004  0002  0000
7191 Circunvalación   D-07 JAL 06727  4960  6448  5453  5102  5642  5107  4575  3393  2916
7192 Zona Dorada      D-12 PUE 03033  2598  3283  3119  3270  3392  3215  2423  3607  1491
7194 Pueblo Nue.      D-05 QRO 00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7195 Guanajuato       D-05 GTO 00003  0002  0000  0000  0000  0000  0000  0000  0000  0000
7196 Pto. Cancún      D-13 QR  00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7197 Zacatecas        D-06 ZAC 01680  1368  1635  1502  1570  1077  1275  1234  1002   905
7198 Pas. Tabasco     D-12 TAB 00088  0002  0000  0000  0001  0000  0000  0000  0000  0000
7199 Pya. Carmen      D-13 QR  00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7200 Tampico          D-08 TMS 07918  6622  8137  7158  8056  7725  8234  7126  7124  3796
7201 Playas Tijuan    D-10 BC  06668  5505  7178  6080  6806  7702  5863  6931  6585  3802
7202 Oceanía (Exp)    D-01 DF  00001  0001  0002  0000  0000  0000  0000  0000  0000  0000
7203 Cd. Juarez I     D-11 CHI 08446  7494  8791  9138  9357  8970  8952  8923  7343  4948
7204 Durango          D-11 DGO 03372  3794  3641  4781  6111  5120  5419  4478  2076  2051
7205 Zavaleta         D-12 PUE 03628  3359  3423  3078  3345  3661  3420  4367  3807  2338
7206 Pz. San Luis     D-06 SLP 00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7207 Nuevo Laredo     D-08 TMS 04407  2959  4483  4425  5209  4315  3782  3847  4023  2740
7208 Bosque Real      D-07 JAL 05401  4493  4884  4960  5050  8274  7858  7849  7150  4153
7209 Ensenada         D-10 BC  04348  4265  4608  5456  5274  6212  6045  6352  4956  2780
7210 Lm. Chihuahua    D-11 CHI 01959  2140  3521  2627  3608  3705  4303  4404  5147  3506
7211 Cancún Cumbres   D-13 QR  06235  4748  5500  4924  5079  4337  6789  5036  6062  4126
7212 Plaza Kune       D-08 NL  00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7213 Los Mochis       D-11 BC  00005  0000  0000  0000  0000  0000  0000  0000  0000  0000
7215 Colima           D-07 COL 02172  2015  2532  2539  2308  2399  2097  2939  2047  1326
7216 SM Allende II    D-05 GTO 00062   050   046   005   004   005   012   003   003   000
7217 Punto Sur        D-05 QRO 00000  0001  0000  0000  0000  0000  0000  0000  0000  0000
7218 Cd. Juárez II    D-11 CHI 05025  5138  4550  4534  6491  5701  5792  5838  4938  2887
7219 Reynosa          D-08 TMS 02046  1973  3127  2697  3142  3442  3755  3251  1633  2003
7220 Roma Norte       D-02 DF  00001  0001  0001  0000  0000  0000  0000  0000  0000  0000
7221 Lm. Chapul.      D-03 DF  00001  0002  0001  0003  0002  0008  0005  0003  0001  0005
7222 Aldea Tulum      D-13 QR  00001  0001  0000  0000  0000  0000  0000  0000  0000  0000
7223 Península        D-10 BC  02973  2915  2462  4399  3797  4700  4881  4246  4107  2353
7224 Atlixco (Exp)    D-12 PUE 00001  0003  0001  0002  0000  0000  0000  0000  0000  0000
7225 Parque Tepeyac   D-01 DF  03336  2613  2897  3573  3714  3725  3832  3456  2943  1859
7226 Antenas          D-01 DF  02606  2000  2165  2140  2658  1889  2489  2330  2057  1214
7227 Playa Carmen     D-13 QR  04543  7264  6156  7427  5701  5959  5746  4807  4912  2562
7229 Metepec Town Sq  D-01 MEX 03504  2774  4675  4566  3599  3409  3743  4781  3497  2659
7231 Tij Landmark     D-10 BC  03269  2454  3565  3662  4072  3189  3858  3993  3488  1670
7232 Del Valle (Exp)  D-04 DF  00004  0001  0008  0001  0001  0005  0000  0007  0001  0000
7233 Polanco (Exp)    D-03 DF  00001  0001  0001  0002  0001  0000  0000  0000  0000  0000
7234 Rosarito (Exp)   D-10 BC  00001  0009  0008  0002  0000  0000  0000  0000  0000  0000
7235 El Dorado (Exp)  D-12 VER 00001  0002  0004  0002  0000  0000  0000  0000  0000  0000
7236 Avándaro (Exp)   D-01 MEX 00002  0006  0000  0000  0000  0000  0000  0000  0000  0000
7237 Aguascalientes   D-06 AGS 02051  2130  2411  1754  2946  2818  3492  2611  2199  1778
7238 Insurgentes Sur  D-04 DF  00002  0000  0000  0000  0000  0000  0000  0000  0000  0000
7240 Cabo San Lucas   D-10 BCS 02020  1771  2762  2129  2890  2179  2329  2029  1823  1487
7242 Fórum Culiacán   D-11 SIN 01384  1732  1022  1468  1280  2266  1196  1517   867   810
7243 Bosque Real      D-03 MEX 00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7244 Plaza Oriente    D-01 DF  01765  1913  3437  2066  3594  2441  3092  3153  2777  1199
7245 Yácatas (Exp)    D-02 DF  00002  0005  0003  0001  0003  0001  0001  0000  0000  0000
7246 Samara Satélite  D-03 MEX 00890   725  1243  1273   924  1308   910  1581  1264   812
7247 Paseo Querétaro  D-05 QRO 00002  0003  0002  0001  0000  0001  0000  0000  0000  0000
7248 El Pitic (Exp)   D-11 SON 00001  0000  0000  0000  0000  0000  0000  0000  0000  0000
7250 The Park         D-06 SLP 00033  1806  2934  2734  2184  3049  2796  1673   976   000
7252 Av. Toluca       D-02 DF  00345  0000  0000  0000  0000  0000  0000  0000  0000  0000
7253 Álamos Parque    D-05 QRO 00005  0006  0005  0005  0001  0000  0000  0000  0000  0000
7501 e-Commerce       e-CO MEX 05974  4491  5575  5109  9942  6691  4216  4040  4948  3967
;
run;

data Nombre_marcas;
	input Marca 1-4  'Nombre Marca'n $ 5-30;
	datalines;
 16 AQUEON
 19 AVIAN SELECT
 49 CONCEPTUAL CREATIONS PET
 73 FANCY FEAST
 95 HAGEN
114 KAYTEE
123 LEE'S
135 MARINELAND
136 MARSHALL PET
161 PENN PLAX
189 PRO PLAN
203 ROYAL CANIN
207 HILL'S SCIENCE DIET
209 SEACHEM
211 SEAVIEW INC.
227 TETRA
243 WARE
254 ZILLA
255 ZOO MED
284 NATURAL GOURMET
286 BOYU
287 AZOO
306 GLOFISH
371 CANINE CHEWS
372 CHOICE NUTRITION
377 TIER
383 PETMMAL
418 MAZURI
430 MARVELL
445 IMAGITARIUM
457 KRUKETS
458 NUTRIALL
464 FLUVAL
478 LA GALLETERIA
479 CAREFRESH
517 INSTINCT
524 PETCO ZOO
564 LIVELONG HEALTHY & STRONG
589 NATURAL BALANCE
605 WHIMZEES
629 ISTA
656 WILDERNESS
657 CANIDAE PURE
669 HEALTHY SELECT
673 VERSELE-LAGA
677 LUCKY DOG
688 BIRDX
697 ABEPET
702 YOLCAME
713 WHOLEHEARTED
714 LIDERATTO
719 HOGER HOND
721 PETIT MONSTERS
725 FULLTRUST
728 GOOD LOVIN'
729 BARKERS CLUB
731 MUTT
744 UN DOS TREATS
747 SMARTBONES
748 TAMALITOS DOG
760 BLEIZ
761 STRELKA
776 PAW & PANTRY
786 OXBOW
817 OPTIPROT
844 INSTINCT RAW BOOST
845 LIFELIKE
851 NATURAL GOURMET FELINE
852 WHOLEHEARTED SMART SMILE
864 TERRARIA
865 EMERAID
866	WHOLEHEARTED ACTIVE PERFORMANC
868	INSEKT CO
869	LOLLY DOG
871	LES REPAS PLAISIR
873	ORGANOMICS
889	WHOLEHEARTED BAKERY
913	EMERALD PET
919	A&E CAGE CO
929	IKAI
930	CANIDAE PURE PETITE
931	OMEGA ONE
932	POLKADOG
936	N-BONE
937	GET NAKED
946	ROYAL CANIN VETERINARY DIET
947	HILL'S PRESCRIPTION DIET
948	PRO PLAN VETERINARY DIETS
949	FANCY FEAST GOURMET NATURALS
952	CANIDAE GOODNESS
955	MELVINS BARF
956	INABA
957	PRIMEBONES
967	HIGGINS
969	INDOMITABLE PATAGONIA
970	DENTAL PLUS
972	BOUN
973	HAPPY HABITATS
974	HUNGRY PAWS
980	AMITY
981	BRAVERY
991	NOTHING TO HIDE
1000AQUAEL
1001PUP ICE
1004PATAGON RAW
1017GO SOLUTIONS
1019AQUAVITRO
1036SPUNKY PUP TREATS
1049WILD EATS
1054CLAUDIA'S CANINE BAKERY
1055N-BONE FLOSSTA
1059CANNIET
1060DENTAL-LINE
1063DOLE
1064WAGGGYS
1073WHISKERS&CHEEKS
1076KIOTOYS
1081ZANU
1085ORGANIMALS
1093ORIJEN
1094ACANA
1096LOVIE
1152BARKIN' BURGER
1186GOOD N TASTY
1187LIFE PROTECTION FORMULA
1188TASTEFULS
1190SUPER DEGY
1191FERPLAST
;
run;



*********************************************************************
***************** Construcción de la tabla reporte ******************
*********************************************************************;

proc sql;
	create table tabla_reporte as
	select *
	from tienda_materiales as a
	inner join materiales_marcas as b on a.material = b.material
	inner join nombre_marcas as c on b.marca = c.marca
	inner join ventas as d on d.tienda = a.tienda;
	quit;
run;

proc sql;
	create table tiendas_ventas as
	select distinct tienda, 'Nombre tienda'n, 'Enero 2025'n, 'Febrero 2025'n, 'Marzo 2025'n, 'Abril 2025'n, 'Mayo 2025'n, 'Junio 2025'n, 'Julio 2025'n, 'Agosto 2025'n, 'Septiembre 2025'n, 'Octubre 2025'n
	from tabla_reporte;
	quit;
run;

proc sql;
	create table materiales as
	select distinct material, 'nombre material'n, marca
	from tabla_reporte;
	quit;
run;



proc sort data= work.tabla_reporte;
by tienda ;
run;



*********************************************************************
******************* Consultas en la tabla-reporte *******************
*********************************************************************;

* 1.- Qué tiendas tiene ventas menor a 4000 en abril*;

proc sql;
    create table Ventas_Abril_7120 as
    select distinct Tienda, 'Nombre tienda'n, 'Abril 2025'n  as Ventas_Abril_2025
    from tabla_reporte
    where 'Abril 2025'n < 4000
    order by  'Ventas_Abril_2025'n desc;
quit;

* 2.- Qué material produce azoo? (marca 287)*;

proc sql;
    create table Azoo as
    select distinct marca, 'nombre marca'n, material, 'Nombre Material'n
    from tabla_reporte
    where 'nombre marca'n like 'AZOO';
quit;

* 3.- Extraer toda la info de zoo med (255) *;


proc sql;
    create table ZOO_MED as
    select distinct tienda, marca, 'nombre marca'n, material, 'Nombre Material'n, 'Nombre tienda'n, Distrito, Estado
    from tabla_reporte
    where 'nombre marca'n = 'ZOO MED';
quit;

* 4.- Materiales que empiecen con la letra A y se venda en tiendas con tienda > 7127*;

proc sql;
	create table MA_7127 as
	select tienda, 'Nombre Material'n
	from tabla_reporte
	where 'Nombre material'n like 'A%' and tienda > 7127;
quit;

* 5.- ¿Cuántos materiales hay por tienda? *;

proc sql;
	create table conteo_por_tiendas as
	select 'Nombre tienda'n, count('Nombre material'n) as 'Numero de material'n
	from tabla_reporte
 	Group by 'Nombre tienda'n;
 quit;

 """


***COMENTARIOS SAS***

Durante la elaboración del proyecto hemos de notar aquellas complicaciones que tuvimos, y la forma en la que logramos corregir nuestro código.

En un primer punto podemos ver que al momento de dar de alta nuestra información en las tablas de SAS, sabemos que la forma de separar nuestros datos es por medio de espacios, sin embargo, nuestra Base de Datos cuenta con información alfanumérica que cuenta con uno o más espacios dentro de la misma variable, lo que tuvimos que solucionar definiendo el número de caracteres que cada columna debería de tomar, es por eso que los espacios y el orden dentro de la 1ra sección es lo más importante.

Otra función a notar es la forma en la que declaramos nuestras variables columnas, pues hay veces que en las consultas de SAS las variables dentro del "select" no se detectan de manera correcta, es por eso que hicimos uso de ''n, no que nos permite recordarle a SAS que todo lo que se encuentra dentro de las comillas es el nombre de una variable-columna.

# ***Conclusiones***

La elaboración de los ejercicios nos permitió comprender de mejor manera la gran ventaja que comprende el uso de estas herramientas. Tanto SAS como SQL significan un instrumento de manejo, gestión y explotación de Bases de Datos. Softwares que parecen y se presumen de salida, demuestran que cumplen eficazmente sus porpósitos.
Con ellos, nos damos cuenta podemos elaborar reportes y comprender información muy fácilmente, la dificultad de la tarea radicó en primeramente comprender las tablas, visualizar las uniones y posteriormente escribir las queries.

En esta unidad, aprendimos cómo podemos extraer datos que por sí solos podrían no decir mucho, y observar la información que aportan ya en conjunto.

Representando una aplicación completa de los fundamentos de manipulación de bases de datos en entornos SQL Lite y SAS, integrando teoría, práctica y análisis estratégico. A nivel académico, se logró construir una base de datos relacional a partir de múltiples archivos Excel, realizar uniones entre tablas mediante LEFT JOIN, y ejecutar consultas con operadores lógicos (LIKE, <, >, =), replicando fielmente los procedimientos vistos en clase.

Desde una perspectiva ejecutiva, los insights obtenidos a través de estas consultas revelan oportunidades concretas de mejora y decisión:



*   Tiendas con ventas menores a $4000 en abril 2025 → Identificadas mediante una
consulta SQL con WHERE "Abril 2025" < 4000, esta información permite focalizar estrategias comerciales en sucursales de bajo rendimiento. En SAS, se replicó con PROC SQL, asegurando trazabilidad del análisis.

*   Materiales producidos por marcas específicas (AZOO y ZOO MED) → Extraídos con LIKE '%AZOO%' y WHERE Marca = 287, estas consultas permiten mapear el portafolio de productos por marca. En SAS, se reconstruyó la lógica con DATA y PROC SQL, validando la consistencia entre entornos.

*    Materiales que comienzan con la letra A y se venden en tiendas con ID > 7127 → Esta segmentación, realizada con LIKE 'A%' AND Tienda > 7127, permite identificar productos con potencial de posicionamiento en tiendas de mayor tráfico. El mismo patrón fue replicado en SAS para asegurar la equivalencia de resultados.

*   Distribución geográfica de productos por marca y tienda → Mediante la unión de tablas con LEFT JOIN entre REPORTE_TDA_MARCAS y Tabla3, se enriqueció la base con atributos como distrito y estado, permitiendo visualizar la cobertura territorial. Esta estructura fue replicada en SAS con DATA y MERGE.